return PlaceObj('ModDef', {
	'title', "Big Domes For All",
	'description', "This mod is in early release for Patrons. https://patreon.com/thefiz",
	'image', "Images/thumbnail.png",
	'last_changes', "https://github.com/Surviving-Mars-Mods/Big-Domes-For-All",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"src/*",
		"*.iml",
		".idea/*",
	},
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "FIZZLE1",
			'title', "Fizzle Fuze's Library",
			'version_major', 1,
			'version_minor', 7,
		}),
	},
	'id', "Big-Domes-For-All",
	'pops_desktop_uuid', "e8c48255-8df6-41dd-9484-bc8ffa2db9ea",
	'pops_any_uuid', "1952ba00-6352-4786-bf68-07dcac35de78",
	'author', "Fizzle_Fuze",
	'saved', 1651929629,
	'author', "Fizzle_Fuze",
	'version_major', 1,
	'version_minor', 1,
	'version', 41235,
	'lua_revision', 1009413,
	'saved_with_revision', 1011140,
	'code', {
		"Code/Code.lua",
	},
	'saved', 1645033554,
	'TagResearch', true,
})
